### ISSUE TITLE
Toggles for `Do Not Disturb` and `Keyboard Backlight`

### ISSUE THREAD

**Issue by praharshjain** [jacklandrin/OnlySwitch#83]
**Is your feature request related to a problem? Please describe.**
Need toggles for `Do Not Disturb` and `Keyboard Backlight`

**Describe the solution you'd like**
If possible, please add toggles for `Do Not Disturb` and `Keyboard Backlight`.

For `Do Not Disturb` toggle, we can have options in the settings to configure the time (indefinite, 1 hour etc). Would be great if it can be configured to auto enable on screen sharing.

For `Keyboard Backlight` toggle, the brightness level can be configured in settings, and the toggle would just turn it on or off.

**Describe alternatives you've considered**
Have to use options from Control Center which involves multiple clicks.

**Comment by jacklandrin** [comment]
Thank you for your suggestion. According to the past investigation, I didn't find out a way to implement them in OnlySwitch yet.

**Comment by praharshjain** [comment]
Ah. that's sad. I am not much familiar with Swift and macOS development but will see if I can find a way.

**Comment by jacklandrin** [comment]
> Ah. that's sad. I am not much familiar with Swift and macOS development but will see if I can find a way.

@praharshjain 
1. Regarding Do not Disturb, many scripts are invalid since Monterey. However, I suppose you make shortcuts for this functionality, and add it into OnlySwitch. 
I can give you an example:
<img width="1200" alt="Screenshot 2023-06-18 at 17 58 39" src="https://github.com/jacklandrin/OnlySwitch/assets/3782279/12a080ed-cf8c-4c4a-a873-479add0d8b08">
If you think it is a plan, I can create shortcuts for other focus modes and contribute them to OnlySwitch's shortcuts gallery.
2. Regarding the backlight, I found there isn't a common solution for each MacBook module, I only have three modules on my hand, so can't cover all of them.

**Comment by praharshjain** [comment]
@jacklandrin this would be great! I did not know OnlySwitch supports Shortcuts. I can do a lot of stuff with this now 🤩

**Comment by jacklandrin** [comment]
@praharshjain I updated Do Not Disturb shortcut to gallery, you can check it out.
![WeChat9398eb02266932f7a9267cdbb9edaa09](https://github.com/jacklandrin/OnlySwitch/assets/3782279/3cd375ba-d6bb-4cc2-959b-053786494010)

**Comment by rakalex** [comment]
@jacklandrin here is for reference how you can control the keyboard brightness.

https://github.com/rakalex/mac-brightnessctl
